// tslint:disable
/**
 * Reservation Bear API
 * The documentation of the REST api of Reservation Bear. A reference implementation is available on [Github](https://github.com/Eistbaren/frontend)
 *
 * OpenAPI spec version: 1.1.0
 *
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

export * from './api';
export * from './configuration';
